#!/bin/bash

# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

set -e

echo "Container for sample_client started"

# Add multicast route
route add -net 224.0.0.0/4 dev eth0

# Manually start up the sample_client application when the car_window_controller and gatewayd are already running
# export VSOMEIP_CONFIGURATION=$(pwd)/tests/integration/sample_client/vsomeip.json
# /home/source/bazel-bin/tests/integration/sample_client/sample_client

sleep infinity
